os:
- linux
# Windows fails as well!
- windows
# - osx

language: node_js
node_js:
- 'lts/*'
- 'node'

cache:
- yarn: true
# - apt: true
- directories:
  - "node_modules"

install:
- yarn install

# before_script:
# - yarn run test
# - yarn run test:web
# - yarn run preweb:release

# Wait for: https://github.com/jellyfin/jellyfin-react-client/pull/18
# - yarn run preandroid

# ./node_modules/write-file-atomic/index.js
# Module not found: Can't resolve 'worker_threads' in '/home/travis/build/LucaBernstein/jellyfin-react-client/node_modules/write-file-atomic'
# - yarn run preelectron

after_success:
- yarn run android:release
- yarn run ios:release
- yarn run windows:release
- yarn run electron:release
- yarn run web:release
# branches:
#   only:
#   - master
#   - /^v\d+\.\d+\.\d+/
