os:
- linux
- windows
# - osx

language: node_js
node_js:
- '8'
- '10'
- 'lts/*'
- 'node'

cache:
- apt: true
- directories:
  - "node_modules"
  
install:
- yarn install
- yarn update

before_script:
- yarn run test
- yarn run test:web
- yarn run preweb:release
- yarn run preandroid
- yarn run preelectron
after_success:
- yarn run android:release
- yarn run ios:release
- yarn run windows:release
- yarn run electron:release
- yarn run web:release
# branches:
#   only:
#   - master
#   - /^v\d+\.\d+\.\d+/
