os:
- linux
- osx
- windows

language: node_js
node_js:
- '6'
- '8'
- '10'

cache:
- apt: true
- directories:
  - "node_modules"
  
install:
- yarn install
- yarn update

before_script: yarn test
after_success: yarn run release
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
